
services:
  postgres:
    image: postgres:15
    container_name: choimart-postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - choimart-net
  app:
    build:
      context: ./auth-service
    image: auth-service:latest
    container_name: choimart-app
    env_file:
      - .env
    environment:
      - SPRING_REDIS_HOST=${SPRING_REDIS_HOST}
      - SPRING_REDIS_PORT=${SPRING_REDIS_PORT}
      - SPRING_REDIS_PASSWORD=${SPRING_REDIS_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - choimart-net

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${SPRING_REDIS_PASSWORD}"]
    networks:
      - choimart-net



volumes:
  postgres-data:

networks:
  choimart-net:
